### ISSUE TITLE
Problem with queryParams set to 0.

### ISSUE THREAD

**Issue by DominikTrojcak** [bart-sk/swagger-js-codegen#11]
If any queryParams is set to 0 (Number) in final url it is empty string. 

queryParams:
{offset: 0, limit: 5}

final URL:
 @https://csm.sportnet.online/api/cm/public/ucena-pravnicka-spolocnost/sections/3051/articles?offset=&limit=50

(next issue with limit)

**Comment by martin-cuchta** [comment]
Fixed in https://github.com/bart-sk/swagger-js-codegen/commit/09cf7a9cee06645f77faf1e36fb2d107b7193d5a
