### ISSUE TITLE
Support for response with empty body (e.g. Http 204)

### ISSUE THREAD

**Issue by JurajKavka** [bart-sk/swagger-js-codegen#28]
I case of response status `204 No content`, library tries to parse empty response body as `json` which fails. Before parsing response body as `json`, we need to check status `204`, or response `content-type`.

**Comment by Filipeue** [comment]
Is check for `content-type` enough?

**Comment by borsucok** [comment]
@adyhnat rovno aj toto vyriesme. Ak pride response 204, tak vratime tiez len response objekt.
